SELECT
    CASE WHEN MARKS < 70 THEN NULL
        ELSE NAME END AS NAME
    , CASE WHEN MARKS = 100 THEN 10
        ELSE CEIL((MARKS+1)/10) END AS MARK
    , MARKS
FROM STUDENTS
ORDER BY MARK DESC, NAME ASC;